# Generated by Django 3.0.2 on 2020-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200116_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeed',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
