# Generated by Django 3.0.2 on 2020-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200116_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeed',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
