# Generated by Django 3.0.2 on 2020-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200116_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeed',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='feeed',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
