# Generated by Django 3.0.2 on 2020-01-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subjeck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjeck',
            new_name='Bots',
        ),
    ]
